# Generated by Django 2.2.4 on 2019-08-15 01:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Housecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.IntegerField()),
                ('person', models.CharField(max_length=20)),
                ('use', models.CharField(max_length=20)),
                ('comment', models.CharField(default='-', max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2019, 8, 15, 1, 22, 45, 126859, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Memocond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('lat', models.FloatField(default=37.5400399, max_length=100)),
                ('lon', models.FloatField(default=127.09341909999999, max_length=100)),
                ('locate', models.CharField(default='aa', max_length=50)),
                ('temp', models.IntegerField(default=30)),
                ('humi', models.IntegerField(default=30)),
                ('weat', models.CharField(default='bb', max_length=20)),
                ('date', models.DateField(default=datetime.datetime(2019, 8, 15, 1, 22, 45, 126396, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Roomcond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(default=0)),
                ('humi', models.IntegerField(default=0)),
                ('motion', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.datetime(2019, 8, 15, 1, 22, 45, 55243, tzinfo=utc))),
            ],
        ),
    ]
