# Generated by Django 2.2.4 on 2019-08-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housecond',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='memocond',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roomcond',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
