# Generated by Django 2.2.4 on 2019-08-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmos', '0002_auto_20190809_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housecond',
            name='date',
            field=models.DateField(),
        ),
    ]
