# Generated by Django 2.2.4 on 2019-08-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmos', '0002_auto_20190815_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='memocond',
            name='person',
            field=models.CharField(default='cc', max_length=50),
        ),
    ]
