# Generated by Django 2.2.4 on 2019-08-09 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmos', '0003_auto_20190809_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memocond',
            old_name='gps',
            new_name='locate',
        ),
        migrations.AddField(
            model_name='memocond',
            name='lat',
            field=models.FloatField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memocond',
            name='lon',
            field=models.FloatField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housecond',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='memocond',
            name='weat',
            field=models.CharField(max_length=20),
        ),
    ]
