# Generated by Django 2.2.3 on 2019-08-21 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmos', '0003_memocond_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocond',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 8, 21, 9, 11, 48, 937457)),
        ),
    ]
