# Generated by Django 2.2.4 on 2019-08-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmos', '0004_auto_20190809_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocond',
            name='locate',
            field=models.CharField(default='aa', max_length=50),
        ),
        migrations.AlterField(
            model_name='memocond',
            name='weat',
            field=models.CharField(default='bb', max_length=20),
        ),
    ]
