# Generated by Django 2.2.4 on 2019-08-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmos', '0005_auto_20190809_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocond',
            name='lat',
            field=models.FloatField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='memocond',
            name='lon',
            field=models.FloatField(default=2, max_length=100),
        ),
    ]
