# Generated by Django 2.2.4 on 2019-08-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmos', '0006_auto_20190809_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocond',
            name='lat',
            field=models.FloatField(default=37.5400399, max_length=100),
        ),
        migrations.AlterField(
            model_name='memocond',
            name='lon',
            field=models.FloatField(default=127.09341909999999, max_length=100),
        ),
    ]
