# Generated by Django 2.2.3 on 2019-08-21 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmos', '0006_auto_20190821_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocond',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 9, 19, 13, 28348)),
        ),
    ]
