# Generated by Django 2.2.4 on 2019-08-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmos', '0007_auto_20190809_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='memocond',
            name='humi',
            field=models.IntegerField(default=30, max_length=10),
        ),
        migrations.AddField(
            model_name='memocond',
            name='temp',
            field=models.IntegerField(default=30, max_length=10),
        ),
    ]
