# Generated by Django 2.2.3 on 2019-08-21 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pmos', '0007_auto_20190821_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocond',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
