# Generated by Django 2.2.3 on 2019-08-21 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pmos', '0009_auto_20190821_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocond',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 3, 3, 56, 317304, tzinfo=utc)),
        ),
    ]
