# Generated by Django 2.2.3 on 2019-08-21 03:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pmos', '0010_auto_20190821_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocond',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 3, 7, 47, 94356, tzinfo=utc)),
        ),
    ]
